In [1]:
import torch
import numpy as np

In [2]:
device = torch.device("mps")

In [3]:
Wq = torch.tensor(
    [
        [1, 0, 2, 3], 
        [0, 1, 0, 1],
        [2, 0, 0, 2], 
        [0, 1, 2, 1], 
    ],
    device=device
).float()


In [4]:
Wk = torch.tensor(
    [
        [0, 2, 2, 0],
        [1, 0, 0, 3],
        [0, 0, 1, 0],
        [0, 2, 1, 1], 
    ],
    device=device
).float() 

In [5]:
Wv = torch.tensor(
    [
        [0, 1, 0, 2],
        [1, 3, 0, 0],
        [0, 0, 2, 1],
        [0, 2, 2, 1], 
    ],
    device=device
).float()


In [6]:
x1 = torch.tensor([2,0,0,2], device=device).float() 
x2 = torch.tensor([1,1,2,2], device=device).float() 
x3 = torch.tensor([0,2,1,3], device=device).float() 

In [7]:
q3 = Wq @ x3.T
q3

/var/folders/w_/_7kmyrs11p77hyq28r_kfg4h0000gn/T/ipykernel_85682/1046715240.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1682343657571/work/aten/src/ATen/native/TensorShape.cpp:3575.)
  q3 = Wq @ x3.T


tensor([11.,  5.,  6.,  7.], device='mps:0')

In [8]:
k1 = Wk @ x1.T
k2 = Wk @ x2.T
k3 = Wk @ x3.T 

print(f"k1 = {k1}")
print(f"k2 = {k2}")
print(f"k3 = {k3}")

k1 = tensor([0., 8., 0., 2.], device='mps:0')
k2 = tensor([6., 7., 2., 6.], device='mps:0')
k3 = tensor([6., 9., 1., 8.], device='mps:0')


In [9]:
v1 = Wv @ x1.T
v2 = Wv @ x2.T
v3 = Wv @ x3.T

print(f"v1 = {v1.tolist()}")
print(f"v2 = {v2.tolist()}")
print(f"v3 = {v3.tolist()}")

v1 = [4.0, 2.0, 2.0, 2.0]
v2 = [5.0, 4.0, 6.0, 8.0]
v3 = [8.0, 6.0, 5.0, 9.0]


In [10]:
k = torch.stack([k1, k2, k3], dim=0)
k

tensor([[0., 8., 0., 2.],
        [6., 7., 2., 6.],
        [6., 9., 1., 8.]], device='mps:0')

In [11]:
q3 @ k.T

tensor([ 54., 155., 173.], device='mps:0')

In [12]:
alpha_prime_3j = (q3 @ k.T) / 2.0

alpha_prime_3j

tensor([27.0000, 77.5000, 86.5000], device='mps:0')

In [13]:
Wv @ x1

tensor([4., 2., 2., 2.], device='mps:0')

In [14]:
alpha3j = alpha_prime_3j.softmax(dim=0)
alpha3j.tolist()


[1.4435253230330543e-26, 0.00012339460954535753, 0.9998766183853149]

In [15]:
v = torch.stack([v1, v2, v3], dim=0)

y3 = alpha3j @ v
y3.tolist()


[7.999629974365234, 5.999753475189209, 5.000123500823975, 8.999876976013184]